CREATE TABLE tblCountry (
CountryID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
Country VARCHAR(50));
GO
CREATE TABLE tblRegion (
RegionID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
CountryID int NOT NULL FOREIGN KEY REFERENCES tblCountry(CountryID),
Area VARCHAR(255));
GO
CREATE TABLE tblCity (
CityID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
City VARCHAR(50));
GO
CREATE TABLE tblSuburb (
SuburbID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
CityID int NOT NULL FOREIGN KEY REFERENCES tblCity(CityID),
Suburb VARCHAR(100),
ZipCode DECIMAL(4,0));
GO
CREATE TABLE tblStore (
StoreID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
SuburbID int NOT NULL FOREIGN KEY REFERENCES tblSuburb(SuburbID),
Store VARCHAR(50));
GO
CREATE TABLE tblUser (
ChefID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
FirstName VARCHAR(30),
LastName VARCHAR(50),
Email VARCHAR(255),
UserName VARCHAR(255),
RoleID int NOT NULL FOREIGN KEY REFERENCES tblRole(RoleID),
Password VARCHAR(255));
GO

CREATE TABLE tblCategory(
CategoryID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
Category VARCHAR(255) NOT NULL);
GO
CREATE TABLE tblRecipe (
RecipeID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
Title VARCHAR(255) NOT NULL,
Method VARCHAR(1000) NOT NULL,
CategoryID int NOT NULL FOREIGN KEY REFERENCES tblCategory(CategoryID),
ChefID int NOT NULL FOREIGN KEY REFERENCES tblChef(ChefID),
RegionID int NOT NULL FOREIGN KEY REFERENCES tblRegion(RegionID));
GO
CREATE TABLE tblIngredient (
IngredientID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
Ingredient VARCHAR(25));
GO
CREATE TABLE tblRecipeIngredientBridge (
RIBridgeID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
RecipeID int NOT NULL FOREIGN KEY REFERENCES tblRecipe(RecipeID),
IngredientID int FOREIGN KEY REFERENCES tblIngredient(IngredientID));
GO
CREATE TABLE tblIngredientStoreBridge (
ISBridgeID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
IngredientID int NOT NULL FOREIGN KEY REFERENCES tblIngredient(IngredientID),
StoreID int NOT NULL FOREIGN KEY REFERENCES tblStore(StoreID));
GO
